// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg5wF3AJ9mK7rjhG8LaUQOGzTNsTBIsyQ',
    appId: '1:416253107871:web:e7bb16bbe6082d0fb50caa',
    messagingSenderId: '416253107871',
    projectId: 'side-project-28255',
    authDomain: 'side-project-28255.firebaseapp.com',
    storageBucket: 'side-project-28255.appspot.com',
    measurementId: 'G-FZBJ3HXF0Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUuKgS4MQbL1U_MO_-kO3BX47GYWXuxJc',
    appId: '1:416253107871:android:67085bb977dafb03b50caa',
    messagingSenderId: '416253107871',
    projectId: 'side-project-28255',
    storageBucket: 'side-project-28255.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYG7EDKIMks04tsQ_3p_G1mOKaYB9QujM',
    appId: '1:416253107871:ios:1ed1ec9690bb863ab50caa',
    messagingSenderId: '416253107871',
    projectId: 'side-project-28255',
    storageBucket: 'side-project-28255.appspot.com',
    iosClientId: '416253107871-e69mtbh4hm9i6a1pgk7ldkbotpqufrm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.sideProj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYG7EDKIMks04tsQ_3p_G1mOKaYB9QujM',
    appId: '1:416253107871:ios:fb92f9b7bebb9c8db50caa',
    messagingSenderId: '416253107871',
    projectId: 'side-project-28255',
    storageBucket: 'side-project-28255.appspot.com',
    iosClientId: '416253107871-bk7s0d5tcrfsjrkuo0pq2mk5r2flebbi.apps.googleusercontent.com',
    iosBundleId: 'com.example.sideProj.RunnerTests',
  );
}